name: Privacy check
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  privacy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ZunairaAli18/SourceToSink/action@v1
        with:
          bob-api-key: ${{ secrets.BOB_API_KEY }}